# Generated by Django 5.2.16 on 2026-07-11 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_studentprofile_forecast_calibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('attempt_submitted', 'Attempt Submitted'), ('hint_issued', 'Hint Issued'), ('diagnostic_started', 'Diagnostic Started'), ('diagnostic_submitted', 'Diagnostic Submitted'), ('mock_started', 'Mock Started'), ('mock_submitted', 'Mock Submitted'), ('expert_review_completed', 'Expert Review Completed'), ('plan_rebuilt', 'Plan Rebuilt'), ('plan_change_logged', 'Plan Change Logged'), ('review_completed', 'Review Completed'), ('trajectory_assigned', 'Trajectory Assigned'), ('trajectory_transition', 'Trajectory Transition')], max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
