# Generated by Django 5.2.16 on 2026-07-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('attempt_submitted', 'Attempt Submitted'), ('hint_issued', 'Hint Issued'), ('hint_blocked_by_guardrail', 'Hint Blocked By Guardrail'), ('diagnostic_started', 'Diagnostic Started'), ('diagnostic_submitted', 'Diagnostic Submitted'), ('mock_started', 'Mock Started'), ('mock_submitted', 'Mock Submitted'), ('expert_review_completed', 'Expert Review Completed'), ('plan_rebuilt', 'Plan Rebuilt'), ('plan_change_logged', 'Plan Change Logged'), ('review_completed', 'Review Completed'), ('trajectory_assigned', 'Trajectory Assigned'), ('trajectory_transition', 'Trajectory Transition')], max_length=64),
        ),
    ]
