# Generated by Django 5.2.15 on 2026-08-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_studentprofile_forecast_calibration_and_more'),
        ('events', '0004_alter_event_event_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', '-created_at'], name='event_type_recent'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['student', '-created_at'], name='event_student_recent'),
        ),
    ]
