# Generated by Django 5.2.15 on 2026-08-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_event_type_recent_event_event_student_recent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('attempt_submitted', 'Attempt Submitted'), ('hint_issued', 'Hint Issued'), ('hint_blocked_by_guardrail', 'Hint Blocked By Guardrail'), ('diagnostic_started', 'Diagnostic Started'), ('diagnostic_submitted', 'Diagnostic Submitted'), ('mock_started', 'Mock Started'), ('mock_submitted', 'Mock Submitted'), ('expert_review_completed', 'Expert Review Completed'), ('plan_rebuilt', 'Plan Rebuilt'), ('plan_change_logged', 'Plan Change Logged'), ('review_completed', 'Review Completed'), ('trajectory_assigned', 'Trajectory Assigned'), ('trajectory_transition', 'Trajectory Transition'), ('target_score_changed', 'Target Score Changed'), ('xp_awarded', 'Xp Awarded'), ('streak_advanced', 'Streak Advanced'), ('streak_reset', 'Streak Reset'), ('quest_completed', 'Quest Completed'), ('admin_action', 'Admin Action')], max_length=64),
        ),
    ]
