# Generated by Django 5.2.15 on 2026-07-03 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "start_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("predicted_score", models.PositiveSmallIntegerField()),
                ("target_score", models.PositiveSmallIntegerField()),
                ("average_mastery", models.FloatField(default=0)),
                ("weak_topics", models.JSONField(blank=True, default=list)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_snapshots",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_reports",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "week_start"), name="uniq_weekly_report"
                    )
                ],
            },
        ),
    ]
