# Generated by Django 5.2.15 on 2026-07-31 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_studentprofile_forecast_calibration_and_more'),
        ('mocks', '0002_mockexam_duration_minutes_and_more'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_primary', models.FloatField()),
                ('actual_primary', models.FloatField()),
                ('error', models.FloatField()),
                ('calibration_after', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mock_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_observations', to='mocks.mockexamresult')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_observations', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
