# Generated by Django 5.2.15 on 2026-07-03 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("content", "0001_initial"),
        ("knowledge", "0001_initial"),
        ("mocks", "0001_initial"),
        ("practice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertReviewRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solution_file", models.FileField(upload_to="solutions/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("in_review", "In Review"),
                            ("reviewed", "Reviewed"),
                            ("needs_resubmission", "Needs Resubmission"),
                        ],
                        default="submitted",
                        max_length=32,
                    ),
                ),
                ("sla_hours", models.PositiveSmallIntegerField(default=48)),
                ("score_by_criteria", models.JSONField(blank=True, default=dict)),
                (
                    "total_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "lost_points",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.assignment",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="practice.attempt",
                    ),
                ),
                (
                    "mock_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expert_reviews",
                        to="mocks.mockexamresult",
                    ),
                ),
                (
                    "related_nodes",
                    models.ManyToManyField(blank=True, to="knowledge.knowledgenode"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews_done",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_reviews",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
        ),
    ]
