# Generated by Django 5.2.16 on 2026-07-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertreviewrequest',
            name='error_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
