# Generated by Django 5.2.15 on 2026-07-30 17:00

import apps.expert_review.storage
import apps.expert_review.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_review', '0002_expertreviewrequest_error_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertreviewrequest',
            name='solution_file',
            field=models.FileField(storage=apps.expert_review.storage.private_media_storage, upload_to=apps.expert_review.storage.solution_upload_path, validators=[apps.expert_review.validators.validate_solution_upload]),
        ),
    ]
