# Generated by Django 5.2.15 on 2026-08-15 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_solutionpath_solutionstep'),
        ('expert_review', '0003_alter_expertreviewrequest_solution_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionStepMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('done', 'Выполнен верно'), ('wrong', 'Выполнен с ошибкой'), ('missing', 'Не выполнен')], max_length=16)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_marks', to='expert_review.expertreviewrequest')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='content.solutionstep')),
            ],
            options={
                'ordering': ['review_id', 'step__order'],
                'constraints': [models.UniqueConstraint(fields=('review', 'step'), name='uniq_review_step')],
            },
        ),
    ]
