# Generated by Django 5.2.15 on 2026-09-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_review', '0004_solutionstepmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertreviewrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('reviewed', 'Reviewed'), ('needs_resubmission', 'Needs Resubmission')], default='submitted', max_length=32),
        ),
    ]
