# Generated by Django 5.2.15 on 2026-07-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="forecast_calibration",
            field=models.FloatField(default=0),
        ),
    ]
