# Generated by Django 5.2.15 on 2026-07-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentgroup_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='forecast_calibration',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='calibration_samples',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='primary_calibration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='primary_error_variance',
            field=models.FloatField(default=0),
        ),
    ]
