# Generated by Django 5.2.15 on 2026-07-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="reference_solution",
            field=models.TextField(blank=True),
        ),
    ]
