# Generated by Django 5.2.15 on 2026-07-30 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_lesson_video_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('statement', models.TextField()),
                ('correct_answer', models.CharField(blank=True, max_length=200)),
                ('reference_solution', models.TextField(blank=True)),
                ('max_score', models.PositiveSmallIntegerField(default=1)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('change_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.assignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assignment_id', '-number'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'number'), name='uniq_assignment_version')],
            },
        ),
    ]
