# Generated by Django 5.2.15 on 2026-08-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_dailychallenge_homework_homeworktask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_provider',
            field=models.CharField(choices=[('kinescope', 'Kinescope'), ('youtube', 'YouTube'), ('vk', 'VK Видео'), ('rutube', 'Rutube'), ('other', 'Другой')], default='kinescope', max_length=16),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
