# Generated by Django 5.2.15 on 2026-08-02 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_studentprofile_forecast_calibration_and_more'),
        ('content', '0007_publish_existing_lessons'),
        ('knowledge', '0005_knowledgedependency_no_self_dependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('summary_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='knowledge.knowledgenode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='accounts.studentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'node'), name='uniq_lesson_progress_per_node')],
            },
        ),
    ]
