# Generated by Django 5.2.15 on 2026-08-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='answer_spec',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assignment',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Строка'), ('number', 'Число'), ('expression', 'Выражение'), ('root_set', 'Множество корней'), ('root_families', 'Семейства корней')], default='text', max_length=16),
        ),
    ]
