# Generated by Django 5.2.15 on 2026-08-15 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_assignment_answer_spec_assignment_answer_type'),
        ('knowledge', '0006_knowledgedependency_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('path_type', models.CharField(choices=[('canonical', 'Канонический'), ('alternative', 'Альтернативный')], default='canonical', max_length=16)),
                ('equation_stage', models.CharField(blank=True, max_length=300)),
                ('selection_method', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_paths', to='content.assignment')),
            ],
            options={
                'ordering': ['assignment_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SolutionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('stage', models.CharField(choices=[('transform', 'Преобразование'), ('equation', 'Решение простого уравнения'), ('algebra', 'Алгебраическое решение'), ('constraints', 'Ограничения и допустимость'), ('selection', 'Отбор и проверка'), ('check', 'Контроль ответа'), ('format', 'Оформление')], default='equation', max_length=16)),
                ('role', models.CharField(choices=[('primary', 'Ключевой шаг'), ('supporting', 'Вспомогательный шаг')], default='primary', max_length=16)),
                ('signal', models.CharField(choices=[('strong', 'Сильный сигнал'), ('weak', 'Слабый сигнал')], default='strong', max_length=16)),
                ('is_required', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=300)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solution_steps', to='knowledge.knowledgenode')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='content.solutionpath')),
            ],
            options={
                'ordering': ['path_id', 'order'],
                'constraints': [models.UniqueConstraint(fields=('path', 'order'), name='uniq_step_order')],
            },
        ),
    ]
