# Generated by Django 5.2.15 on 2026-08-22 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_assignment_arena_enabled"),
        ("knowledge", "0006_knowledgedependency_kind_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TheoryQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prompt", models.TextField()),
                ("answer_format", models.CharField(choices=[("word", "Одно слово"), ("number", "Число")], default="word", max_length=8)),
                ("correct_answer", models.CharField(max_length=120)),
                ("accepted_answers", models.JSONField(blank=True, default=list)),
                ("format_hint", models.CharField(blank=True, max_length=120)),
                ("difficulty", models.PositiveSmallIntegerField(default=1)),
                ("options", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cluster", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="theory_questions", to="knowledge.topiccluster")),
                ("node", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="theory_questions", to="knowledge.knowledgenode")),
            ],
            options={
                "ordering": ["cluster__order", "difficulty", "id"],
                "indexes": [models.Index(fields=["cluster", "difficulty"], name="theory_cluster_diff")],
            },
        ),
    ]
