# Generated by Django 5.2.16 on 2026-07-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_studentprofile_forecast_calibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('streak_current', models.PositiveIntegerField(default=0)),
                ('streak_best', models.PositiveIntegerField(default=0)),
                ('streak_period_anchor', models.DateField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('title', models.CharField(max_length=160)),
                ('quest_type', models.CharField(choices=[('solve_tasks', 'Решить задачи'), ('complete_reviews', 'Завершить повторы'), ('finish_plan_items', 'Выполнить пункты плана')], max_length=32)),
                ('target_count', models.PositiveIntegerField()),
                ('progress_count', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('reward_xp', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_quests', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['week_start', 'quest_type'],
                'constraints': [models.UniqueConstraint(fields=('student', 'week_start', 'quest_type'), name='unique_student_weekly_quest_type')],
            },
        ),
    ]
