# Generated by Django 5.2.15 on 2026-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamificationprofile',
            name='streak_freezes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='streak_frozen_periods',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
