# Generated by Django 5.2.15 on 2026-08-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_twofactordevice'),
        ('gamification', '0002_gamificationprofile_streak_freezes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField(unique=True)),
                ('ends_on', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Идёт'), ('closed', 'Завершён')], default='active', max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='league',
            field=models.CharField(choices=[('delta', 'Дельта'), ('gamma', 'Гамма'), ('omega', 'Омега'), ('beta', 'Бетта'), ('alpha', 'Альфа'), ('sigma', 'Сигма')], default='delta', max_length=16),
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='leagues_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LeagueCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(choices=[('delta', 'Дельта'), ('gamma', 'Гамма'), ('omega', 'Омега'), ('beta', 'Бетта'), ('alpha', 'Альфа'), ('sigma', 'Сигма')], max_length=16)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='gamification.leagueseason')),
            ],
            options={
                'ordering': ['league', 'index'],
            },
        ),
        migrations.CreateModel(
            name='LeagueTrophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(choices=[('delta', 'Дельта'), ('gamma', 'Гамма'), ('omega', 'Омега'), ('beta', 'Бетта'), ('alpha', 'Альфа'), ('sigma', 'Сигма')], max_length=16)),
                ('prize', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to='gamification.leagueseason')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_trophies', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeagueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_filler', models.BooleanField(default=False)),
                ('filler_index', models.PositiveSmallIntegerField(default=0)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('place', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('promoted', models.BooleanField(default=False)),
                ('coins_awarded', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gamification.leaguecohort')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_memberships', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-xp', 'joined_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('cohort', 'student'), name='uniq_cohort_student')],
            },
        ),
        migrations.AddConstraint(
            model_name='leaguecohort',
            constraint=models.UniqueConstraint(fields=('season', 'league', 'index'), name='uniq_league_cohort'),
        ),
        migrations.AddConstraint(
            model_name='leaguetrophy',
            constraint=models.UniqueConstraint(fields=('student', 'season', 'league'), name='uniq_league_trophy'),
        ),
    ]
