# Generated by Django 5.2.15 on 2026-09-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_leagueseason_gamificationprofile_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguetrophy',
            name='place',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
