# Generated by Django 5.2.15 on 2026-09-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_leaguetrophy_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguetrophy',
            name='trophy',
            field=models.BooleanField(default=False),
        ),
    ]
