# Generated by Django 5.2.15 on 2026-07-04 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="knowledgenode",
            options={"ordering": ["cluster__order", "order"]},
        ),
        migrations.AddField(
            model_name="knowledgenode",
            name="ege_task_numbers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="knowledgenode",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="skillmastery",
            name="last_practiced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skillmastery",
            name="peak_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="skillmastery",
            name="peak_mastery",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="topiccluster",
            name="color",
            field=models.CharField(default="#58cc02", max_length=7),
        ),
        migrations.AlterField(
            model_name="skillmastery",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("practiced", "Practiced"),
                    ("mastered", "Mastered"),
                    ("decayed", "Decayed"),
                ],
                default="not_started",
                max_length=16,
            ),
        ),
    ]
