# Generated by Django 5.2.16 on 2026-07-12 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_knowledgenode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedependency',
            name='min_mastery',
            field=models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='минимальное освоение, %'),
        ),
    ]
