# Generated by Django 5.2.15 on 2026-07-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_knowledgedependency_min_mastery'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgenode',
            name='hours_estimate',
            field=models.FloatField(default=0),
        ),
    ]
