# Generated by Django 5.2.15 on 2026-08-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_knowledgenode_hours_estimate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='knowledgedependency',
            constraint=models.CheckConstraint(condition=models.Q(('node', models.F('prerequisite')), _negated=True), name='no_self_dependency'),
        ),
    ]
