# Generated by Django 5.2.15 on 2026-08-14 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_knowledgedependency_no_self_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedependency',
            name='kind',
            field=models.CharField(choices=[('prerequisite', 'Обязательная'), ('supports', 'Поддерживающая')], default='prerequisite', max_length=16),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='assessment_mode',
            field=models.CharField(choices=[('deterministic', 'Проверяется автоматически'), ('rubric', 'Проверяется экспертом')], default='deterministic', max_length=16),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='group_aggregation',
            field=models.CharField(choices=[('average', 'Среднее по детям'), ('minimum', 'Минимум по детям')], default='average', max_length=16),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='is_cross_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='layer',
            field=models.CharField(choices=[('subject', 'Предмет'), ('exam_readiness', 'Экзаменационное оформление')], default='subject', max_length=16),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='node_type',
            field=models.CharField(choices=[('atomic', 'Навык'), ('group', 'Папка')], default='atomic', max_length=16),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='knowledge.knowledgenode'),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='skill_class',
            field=models.CharField(choices=[('procedural', 'Приём'), ('reasoning', 'Рассуждение'), ('cross_cutting', 'Сквозной навык'), ('proof', 'Обоснование'), ('formatting', 'Оформление'), ('concept_group', 'Понятийная группа')], default='procedural', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='knowledgenode',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='no_self_parent'),
        ),
    ]
