# Generated by Django 5.2.16 on 2026-10-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_renumber_ege_tasks_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmastery',
            name='retention_days',
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='skillmastery',
            name='review_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
