# Generated by Django 5.2.16 on 2026-10-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_skillmastery_retention_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmastery',
            name='last_retention_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
