# Generated by Django 5.2.15 on 2026-07-03 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assignments",
                    models.ManyToManyField(
                        related_name="mock_exams", to="content.assignment"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MockExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("part1_checked", "Part1 Checked"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                ("primary_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "scaled_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="mocks.mockexam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_results",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
        ),
    ]
