# Generated by Django 5.2.15 on 2026-07-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockexam",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(default=235),
        ),
        migrations.AddField(
            model_name="mockexamresult",
            name="part2_primary_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mockexamresult",
            name="time_expired",
            field=models.BooleanField(default=False),
        ),
    ]
