# Generated by Django 5.2.15 on 2026-09-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0002_mockexam_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexamresult',
            name='draft_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mockexamresult',
            name='draft_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mockexamresult',
            name='draft_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockexamresult',
            name='forecast_at_start',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
