# Generated by Django 5.2.16 on 2026-10-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0003_mockexamresult_draft_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexam',
            name='kind',
            field=models.CharField(choices=[('full', 'Полный пробник'), ('part1_variant', 'Вариант части 1')], default='full', max_length=16),
        ),
    ]
