# Generated by Django 5.2.16 on 2026-07-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistakebacklogitem',
            name='error_type',
            field=models.CharField(choices=[('algebraic_slip', 'Algebraic Slip'), ('arithmetic_slip', 'Arithmetic Slip'), ('wrong_method', 'Wrong Method'), ('incomplete_argument', 'Incomplete Argument'), ('rubric_miss', 'Rubric Miss'), ('graph_misread', 'Graph Misread'), ('misread_condition', 'Misread Condition'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
    ]
