# Generated by Django 5.2.15 on 2026-07-30 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_assignmentversion'),
        ('practice', '0002_mistakebacklogitem_error_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='assignment_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='content.assignmentversion'),
        ),
    ]
