# Generated by Django 5.2.15 on 2026-08-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_studentprofile_forecast_calibration_and_more'),
        ('content', '0008_lessonprogress'),
        ('diagnostics', '0001_initial'),
        ('mocks', '0002_mockexam_duration_minutes_and_more'),
        ('practice', '0004_backfill_attempt_versions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['student', '-created_at'], name='attempt_student_recent'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['student', 'assignment', 'is_correct'], name='attempt_solved'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['mock_result'], name='attempt_mock_result'),
        ),
        migrations.AddIndex(
            model_name='reviewschedule',
            index=models.Index(fields=['status', 'due_date'], name='review_due_queue'),
        ),
    ]
