# Generated by Django 5.2.15 on 2026-08-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_attempt_attempt_student_recent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='context',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('diagnostic', 'Diagnostic'), ('mock', 'Mock'), ('review', 'Review'), ('arena', 'Arena')], default='lesson', max_length=16),
        ),
    ]
