# Generated by Django 5.2.16 on 2026-10-03 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0012_theoryquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключ')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Состояние бота',
                'verbose_name_plural': 'Состояние бота',
            },
        ),
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('tone_of_voice', models.TextField(blank=True, verbose_name='Тон голоса')),
                ('good_post_examples', models.TextField(blank=True, verbose_name='Примеры хороших постов')),
                ('forbidden_phrases', models.JSONField(blank=True, default=list, verbose_name='Запретные формулировки')),
                ('competitors', models.JSONField(blank=True, default=list, verbose_name='Конкуренты')),
                ('evergreen_topics', models.JSONField(blank=True, default=list, verbose_name='Вечнозелёные темы')),
                ('signature', models.CharField(blank=True, max_length=500, verbose_name='Подпись')),
                ('hashtags', models.JSONField(blank=True, default=list, verbose_name='Хэштеги')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Дата ЕГЭ')),
                ('language', models.CharField(default='ru', max_length=10, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Профиль бренда',
                'verbose_name_plural': 'Профиль бренда',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('vk_clips', 'VK Клипы'), ('rutube', 'Rutube'), ('dzen', 'Дзен'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=20, verbose_name='Платформа')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('external_id', models.CharField(max_length=200, verbose_name='Внешний идентификатор')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('mode', models.CharField(choices=[('manual', 'Ручной'), ('auto_safe', 'Автоматический для безопасных рубрик')], default='manual', max_length=16, verbose_name='Режим')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('audience', models.CharField(choices=[('students', 'Ученики'), ('parents', 'Родители'), ('both', 'Все')], max_length=16, verbose_name='Аудитория')),
                ('source_kind', models.CharField(choices=[('assignment_of_day', 'Задача дня'), ('lesson_tip', 'Совет из урока'), ('exam_countdown', 'Отсчёт до ЕГЭ'), ('staff_idea', 'Идея сотрудника'), ('evergreen', 'Вечнозелёная тема')], max_length=32, verbose_name='Источник')),
                ('prompt_hint', models.TextField(blank=True, verbose_name='Подсказка для промпта')),
                ('risk', models.CharField(choices=[('low', 'Низкий'), ('high', 'Высокий')], default='high', max_length=8, verbose_name='Риск')),
                ('autopublish_allowed', models.BooleanField(default=False, verbose_name='Автопубликация разрешена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео')], default='text', max_length=8, verbose_name='Вид')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('checking', 'Проверка'), ('needs_review', 'Нужно согласование'), ('needs_human', 'Нужен человек'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('rewriting', 'Переписывается'), ('scheduled', 'Запланирован'), ('published', 'Опубликован'), ('failed', 'Ошибка')], default='draft', max_length=16, verbose_name='Статус')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('scheduled_for', models.DateTimeField(verbose_name='Время публикации')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано')),
                ('external_message_id', models.CharField(blank=True, max_length=200, verbose_name='ID сообщения')),
                ('source_ref', models.CharField(blank=True, max_length=200, verbose_name='Ссылка на источник')),
                ('group_key', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Группа публикаций')),
                ('rewrite_count', models.PositiveSmallIntegerField(default=0, verbose_name='Число переписываний')),
                ('review_notes', models.TextField(blank=True, verbose_name='Комментарий согласования')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Причина ошибки')),
                ('views', models.PositiveIntegerField(blank=True, null=True, verbose_name='Просмотры')),
                ('reactions', models.PositiveIntegerField(blank=True, null=True, verbose_name='Реакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='social_agent.channel', verbose_name='Канал')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='social_agent.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], max_length=8, verbose_name='Вид')),
                ('file', models.FileField(upload_to='social_agent/', verbose_name='Файл')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность, сек.')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='social_agent.post', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
            },
        ),
        migrations.CreateModel(
            name='LlmCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('draft', 'Черновик'), ('rewrite', 'Переписывание'), ('check', 'Проверка')], max_length=16, verbose_name='Назначение')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Модель')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='Входные токены')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='Выходные токены')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='social_agent.post', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Вызов LLM',
                'verbose_name_plural': 'Вызовы LLM',
            },
        ),
        migrations.CreateModel(
            name='PostCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('banned_phrase', 'Запретная формулировка'), ('number_whitelist', 'Белый список чисел'), ('answer_integrity', 'Целостность ответа'), ('length', 'Длина'), ('competitor', 'Конкурент'), ('personal_data', 'Персональные данные')], max_length=24, verbose_name='Проверка')),
                ('passed', models.BooleanField(verbose_name='Пройдена')),
                ('detail', models.TextField(blank=True, verbose_name='Подробности')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='social_agent.post', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Проверка публикации',
                'verbose_name_plural': 'Проверки публикаций',
            },
        ),
        migrations.CreateModel(
            name='ContentIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('body', models.TextField(verbose_name='Текст')),
                ('audience', models.CharField(choices=[('students', 'Ученики'), ('parents', 'Родители'), ('both', 'Все')], max_length=16, verbose_name='Аудитория')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использовано')),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_ideas', to='social_agent.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Идея контента',
                'verbose_name_plural': 'Идеи контента',
            },
        ),
        migrations.CreateModel(
            name='RubricSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('time', models.TimeField(verbose_name='Время')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_slots', to='social_agent.channel', verbose_name='Канал')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='social_agent.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Слот рубрики',
                'verbose_name_plural': 'Слоты рубрик',
            },
        ),
        migrations.CreateModel(
            name='SocialLessonPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда одобрено')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто одобрил')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_permission', to='content.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Разрешение на урок',
                'verbose_name_plural': 'Разрешения на уроки',
            },
        ),
        migrations.CreateModel(
            name='SocialTaskPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда одобрено')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто одобрил')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_permission', to='content.assignment', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Разрешение на задачу',
                'verbose_name_plural': 'Разрешения на задачи',
            },
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('channel', 'rubric', 'scheduled_for'), name='social_unique_planned_post'),
        ),
    ]
