# Generated by Django 5.2.15 on 2026-08-18 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_twofactordevice'),
        ('content', '0010_solutionpath_solutionstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('speed', 'Нарешивание на скорость'), ('quiz', 'Квиз'), ('board', 'Своя игра')], default='speed', max_length=16)),
                ('status', models.CharField(choices=[('invited', 'Приглашение отправлено'), ('active', 'Идёт'), ('finished', 'Завершена'), ('declined', 'Отклонена')], default='active', max_length=16)),
                ('ege_task_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bot_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seconds_per_question', models.PositiveSmallIntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_created', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bot', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('total_time_ms', models.PositiveIntegerField(default=0)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='arena.match')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-score', 'total_time_ms'],
            },
        ),
        migrations.CreateModel(
            name='MatchQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('points', models.PositiveSmallIntegerField(default=100)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.assignment')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='arena.match')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MatchAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.CharField(blank=True, max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_ms', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='arena.matchparticipant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='arena.matchquestion')),
            ],
            options={
                'ordering': ['question__order'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Заявка отправлена'), ('accepted', 'В друзьях'), ('declined', 'Отклонено')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('from_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to='accounts.studentprofile')),
                ('to_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('from_student', 'to_student'), name='uniq_friendship_pair'), models.CheckConstraint(condition=models.Q(('from_student', models.F('to_student')), _negated=True), name='no_self_friendship')],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', '-created_at'], name='match_status_recent'),
        ),
        migrations.AddConstraint(
            model_name='matchparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('match', 'student'), name='uniq_match_student'),
        ),
        migrations.AddConstraint(
            model_name='matchquestion',
            constraint=models.UniqueConstraint(fields=('match', 'order'), name='uniq_match_question_order'),
        ),
        migrations.AddConstraint(
            model_name='matchanswer',
            constraint=models.UniqueConstraint(fields=('participant', 'question'), name='uniq_participant_question'),
        ),
    ]
