# Generated by Django 5.2.15 on 2026-08-18 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_twofactordevice'),
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_ranked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ArenaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=1000)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arena_profile', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='MatchmakingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('speed', 'Нарешивание на скорость'), ('quiz', 'Квиз'), ('board', 'Своя игра')], default='quiz', max_length=16)),
                ('ege_task_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(default=1000)),
                ('status', models.CharField(choices=[('waiting', 'Ищет соперника'), ('matched', 'Соперник найден'), ('cancelled', 'Отменена')], default='waiting', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='arena.match')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_tickets', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'mode', 'created_at'], name='ticket_queue')],
            },
        ),
    ]
