# Generated by Django 5.2.15 on 2026-08-22 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_match_is_ranked_arenaprofile_matchmakingticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='limit_kind',
            field=models.CharField(choices=[('questions', 'До набора задач'), ('time', 'На время')], default='questions', max_length=16),
        ),
        migrations.AddField(
            model_name='match',
            name='time_limit_seconds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='turn_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='arena.matchparticipant'),
        ),
        migrations.AddField(
            model_name='matchanswer',
            name='chosen_option',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchanswer',
            name='points_delta',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchquestion',
            name='bot_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchquestion',
            name='bot_time_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchquestion',
            name='column',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchquestion',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchquestion',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='matchquestion',
            name='picked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_questions', to='arena.matchparticipant'),
        ),
        migrations.AddField(
            model_name='matchquestion',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchquestion',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_questions', to='arena.matchparticipant'),
        ),
    ]
