# Generated by Django 5.2.15 on 2026-08-22 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_match_limit_kind_match_time_limit_seconds_and_more'),
        ('content', '0012_theoryquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchquestion',
            name='theory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.theoryquestion'),
        ),
        migrations.AddField(
            model_name='matchquestion',
            name='topic_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='match',
            name='mode',
            field=models.CharField(choices=[('speed', 'Нарешивание на скорость'), ('quiz', 'Квиз по теории'), ('board', 'Своя игра')], default='speed', max_length=16),
        ),
        migrations.AlterField(
            model_name='matchmakingticket',
            name='mode',
            field=models.CharField(choices=[('speed', 'Нарешивание на скорость'), ('quiz', 'Квиз по теории'), ('board', 'Своя игра')], default='quiz', max_length=16),
        ),
        migrations.AlterField(
            model_name='matchparticipant',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchquestion',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.assignment'),
        ),
    ]
