# Generated by Django 5.2.15 on 2026-08-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0004_matchquestion_theory_matchquestion_topic_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmakingticket',
            name='limit_kind',
            field=models.CharField(choices=[('questions', 'До набора задач'), ('time', 'На время')], default='questions', max_length=16),
        ),
        migrations.AddField(
            model_name='matchmakingticket',
            name='time_limit_seconds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
