# Generated by Django 5.2.15 on 2026-08-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0005_matchmakingticket_limit_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('invited', 'Приглашение отправлено'), ('lobby', 'Сбор игроков'), ('active', 'Идёт'), ('finished', 'Завершена'), ('declined', 'Отклонена'), ('cancelled', 'Отменена')], default='active', max_length=16),
        ),
    ]
