# Generated by Django 5.2.15 on 2026-08-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0006_match_revision_matchparticipant_joined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmakingticket',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
