# Generated by Django 5.2.15 on 2026-08-26 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0007_matchmakingticket_question_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchquestion',
            name='rebound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchquestion',
            name='rebound_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebound_questions', to='arena.matchparticipant'),
        ),
    ]
