# Generated by Django 5.2.15 on 2026-07-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planchangelog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="planchangelog",
            name="acknowledged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="planchangelog",
            name="is_major",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="planchangelog",
            name="reason",
            field=models.CharField(
                choices=[
                    ("inactivity", "Inactivity"),
                    ("poor_mock", "Poor Mock"),
                    ("frequent_mistakes", "Frequent Mistakes"),
                    ("decay", "Decay"),
                    ("manual", "Manual"),
                ],
                max_length=32,
            ),
        ),
    ]
