# Generated by Django 5.2.15 on 2026-08-01 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_knowledgedependency_no_self_dependency'),
        ('planning', '0004_seed_named_trajectories'),
    ]

    operations = [
        migrations.AddField(
            model_name='planchangelog',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_changes', to='knowledge.knowledgenode'),
        ),
    ]
