# Generated by Django 5.2.15 on 2026-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_planchangelog_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplanitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
