# Generated by Django 5.2.15 on 2026-08-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_knowledgedependency_no_self_dependency'),
        ('planning', '0006_studyplanitem_completed_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studyplanitem',
            index=models.Index(fields=['plan', 'status', 'order'], name='plan_item_queue'),
        ),
        migrations.AddIndex(
            model_name='studyplanitem',
            index=models.Index(fields=['plan', 'due_date'], name='plan_item_due'),
        ),
        migrations.AddIndex(
            model_name='studyplanitem',
            index=models.Index(fields=['status', 'completed_at'], name='plan_item_done_at'),
        ),
    ]
