# Generated by Django 5.2.15 on 2026-09-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_studyplanitem_plan_item_queue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='unplanned_nodes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
