# Generated by Django 5.2.16 on 2026-10-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_studyplanitem_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplanitem',
            name='item_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('practice', 'Practice'), ('review', 'Review'), ('mock', 'Mock'), ('variant', 'Variant')], default='lesson', max_length=16),
        ),
    ]
