"""Разметка задания 13: навыки и связи (WBS 2 v4.1).

Данные лежат в коде, а не загружаются файлом: книга меняется примерно раз
в год, а код даёт версионирование, ревью и проверки в CI бесплатно.
Обновление — заменой этого модуля и запуском `manage.py load_markup`.

Два места, где перенос не дословный, и оба намеренные:

* «обязательная связь» у нас означает ворота. В книге два измерения —
  тип связи и жёсткость, — поэтому воротами становится только
  `prerequisite` с `Hard_dependency=1`; шесть мягких prerequisite
  переносятся как поддерживающие: они объясняют порядок, но ничего не
  закрывают;
* часов в книге нет (правка 3 к методистам), поэтому у всех навыков
  ноль — план подставит дефолт по части экзамена. Способ агрегации папок
  тоже не задан (правка 7): везде среднее.
"""

VERSION = "WBS 2 v4.1"
CLUSTER = {"title": "Тригонометрия (задание 13)", "exam_weight": 2.0, "color": "#4F6BEA"}
EGE_TASK_NUMBERS = [13]

SKILLS = [
    {"code": "SK-MA-0001", "title": "Определять точные значения sin и cos базовых углов", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0002", "title": "Числовая окружность и периодичность", "node_type": "group", "skill_class": "concept_group"},
    {"code": "SK-MA-0003", "title": "Преобразовывать квадрат тригонометрической функции по основному тождеству", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0004", "title": "Применять формулу cos(π−α)=−cos α", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0005", "title": "Преобразовывать cos 2t через sin²t", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0006", "title": "Упрощать квадратные радикалы до точного вида", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0007", "title": "Выполнять равносильные алгебраические преобразования", "node_type": "atomic", "skill_class": "cross_cutting"},
    {"code": "SK-MA-0008", "title": "Факторизация и нулевое произведение", "node_type": "group", "skill_class": "concept_group"},
    {"code": "SK-MA-0009", "title": "Раскладывать квадратный трёхчлен относительно sin t на линейные множители", "node_type": "atomic", "skill_class": "procedural", "parent": "SK-MA-0008"},
    {"code": "SK-MA-0010", "title": "Строить решения sin t=a для табличных и нетабличных a", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0011", "title": "Строить решения cos t=a для табличных и нетабличных a", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0012", "title": "Отбрасывать недопустимые значения sin t и cos t вне [−1;1]", "node_type": "atomic", "skill_class": "reasoning"},
    {"code": "SK-MA-0013", "title": "Объединять семейства решений из нескольких ветвей", "node_type": "atomic", "skill_class": "reasoning"},
    {"code": "SK-MA-0014", "title": "Отбор корней на заданном промежутке", "node_type": "group", "skill_class": "concept_group"},
    {"code": "SK-MA-0015", "title": "Учитывать включённость границ при отборе корней", "node_type": "atomic", "skill_class": "cross_cutting", "parent": "SK-MA-0014"},
    {"code": "SK-MA-0016", "title": "Проверять полноту и отсутствие дублей в наборе корней", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0014"},
    {"code": "SK-MA-0017", "title": "Обосновывать ключевые преобразования развёрнутого решения", "node_type": "atomic", "skill_class": "proof"},
    {"code": "SK-MA-0018", "title": "Разделять решение и ответы по подпунктам экзаменационной задачи", "node_type": "atomic", "skill_class": "formatting"},
    {"code": "SK-MA-0019", "title": "Определять смену функции в формуле приведения", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0020", "title": "Определять знак в формуле приведения по четверти", "node_type": "atomic", "skill_class": "reasoning"},
    {"code": "SK-MA-0021", "title": "Сводить однородное уравнение A sin t+B cos t=0 к tan t=c", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0022", "title": "Преобразовывать sin 2t в произведение 2sin t cos t", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0023", "title": "Приводить угол к сонаправленному в [0;2π) по модулю 2π", "node_type": "atomic", "skill_class": "procedural", "parent": "SK-MA-0002"},
    {"code": "SK-MA-0024", "title": "Определять четверть, опорный угол и знак по единичной окружности", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0002"},
    {"code": "SK-MA-0025", "title": "Выносить общий множитель", "node_type": "atomic", "skill_class": "procedural", "parent": "SK-MA-0008"},
    {"code": "SK-MA-0026", "title": "Применять правило нулевого произведения", "node_type": "atomic", "skill_class": "procedural", "parent": "SK-MA-0008"},
    {"code": "SK-MA-0027", "title": "Отбирать корни на числовой окружности по выделенной дуге", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0014"},
    {"code": "SK-MA-0028", "title": "Отбирать корни через двойные неравенства для параметра", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0014"},
    {"code": "SK-MA-0029", "title": "Решать tan t=a для табличных и нетабличных a в общем виде", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0030", "title": "Решать тригонометрическое уравнение с линейным составным аргументом ax+b", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0031", "title": "Определять точные значения tan и cot базовых углов", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0032", "title": "Применять формулу суммы и разности синуса", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0033", "title": "Определять главное значение и диапазон обратной тригонометрической функции", "node_type": "atomic", "skill_class": "reasoning"},
    {"code": "SK-MA-0034", "title": "Фильтровать семейства решений по знаку тригонометрической функции", "node_type": "atomic", "skill_class": "reasoning"},
    {"code": "SK-MA-0035", "title": "Преобразовывать tan t в отношение sin t к cos t", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0036", "title": "Преобразовывать cos 2t через cos²t−sin²t", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0037", "title": "Использовать чётность и нечётность тригонометрических функций", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0038", "title": "Выбирать подходящую форму формулы двойного угла", "node_type": "atomic", "skill_class": "reasoning"},
    {"code": "SK-MA-0039", "title": "Обосновывать деление на тригонометрическое выражение проверкой нулевого случая", "node_type": "atomic", "skill_class": "reasoning"},
    {"code": "SK-MA-0040", "title": "Сводить квадратное однородное тригонометрическое уравнение к квадратному относительно tan t", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0041", "title": "Факторизовать выражение группировкой", "node_type": "atomic", "skill_class": "procedural", "parent": "SK-MA-0008"},
    {"code": "SK-MA-0042", "title": "Применять формулу разности квадратов", "node_type": "atomic", "skill_class": "procedural", "parent": "SK-MA-0008"},
    {"code": "SK-MA-0043", "title": "Использовать неотрицательность квадрата для исключения ветви", "node_type": "atomic", "skill_class": "reasoning"},
    {"code": "SK-MA-0044", "title": "Переходить от f²(x)=a к ветвям f(x)=±√a", "node_type": "atomic", "skill_class": "procedural"},
    {"code": "SK-MA-0045", "title": "Замена переменной", "node_type": "group", "skill_class": "concept_group"},
    {"code": "SK-MA-0046", "title": "Выбирать замену t=f(x) по структуре уравнения", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0045"},
    {"code": "SK-MA-0047", "title": "Устанавливать достижимый диапазон новой переменной", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0045"},
    {"code": "SK-MA-0048", "title": "Фильтровать алгебраические корни по диапазону замены", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0045"},
    {"code": "SK-MA-0049", "title": "Выполнять обратную замену и возвращаться к исходной переменной", "node_type": "atomic", "skill_class": "procedural", "parent": "SK-MA-0045"},
    {"code": "SK-MA-0050", "title": "ОДЗ и равносильность", "node_type": "group", "skill_class": "concept_group"},
    {"code": "SK-MA-0051", "title": "Выводить ограничения из знаменателей и частично определённых функций", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0050"},
    {"code": "SK-MA-0052", "title": "Применять условие равенства дроби нулю", "node_type": "atomic", "skill_class": "procedural", "parent": "SK-MA-0050"},
    {"code": "SK-MA-0053", "title": "Устранять знаменатель с сохранением исходных ограничений", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0050"},
    {"code": "SK-MA-0054", "title": "Пересекать несколько условий области определения", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0050"},
    {"code": "SK-MA-0055", "title": "Проверять найденные семейства по исходным ограничениям", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0050"},
    {"code": "SK-MA-0056", "title": "Устанавливать условие B(x)≥0 для радикала", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0050"},
    {"code": "SK-MA-0057", "title": "Устанавливать условие B(x)>0 для радикала в знаменателе", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0050"},
    {"code": "SK-MA-0058", "title": "Различать нулевой радикал-множитель и радикал в знаменателе", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0050"},
    {"code": "SK-MA-0059", "title": "Приводить показательные выражения к общему основанию", "node_type": "atomic", "skill_class": "procedural", "cross_domain": True},
    {"code": "SK-MA-0060", "title": "Преобразовывать взаимно обратные степени и отрицательные показатели", "node_type": "atomic", "skill_class": "procedural", "cross_domain": True},
    {"code": "SK-MA-0061", "title": "Переходить от равенства степеней с одинаковым основанием к равенству показателей", "node_type": "atomic", "skill_class": "procedural", "cross_domain": True},
    {"code": "SK-MA-0062", "title": "Устанавливать положительность аргумента логарифма", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0050", "cross_domain": True},
    {"code": "SK-MA-0063", "title": "Устанавливать ненулевое значение логарифма в знаменателе", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0050", "cross_domain": True},
    {"code": "SK-MA-0064", "title": "Преобразовывать логарифмическое равенство в показательную форму или равенство аргументов", "node_type": "atomic", "skill_class": "procedural", "cross_domain": True},
    {"code": "SK-MA-0065", "title": "Обосновывать автоматическое выполнение логарифмического ОДЗ по положительной правой части", "node_type": "atomic", "skill_class": "reasoning", "parent": "SK-MA-0050", "cross_domain": True},
    {"code": "SK-MA-0066", "title": "Решать квадратное уравнение разложением или через дискриминант", "node_type": "atomic", "skill_class": "cross_cutting", "cross_domain": True},
]

EDGES = [
    {"prerequisite": "SK-MA-0023", "node": "SK-MA-0024", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0024", "node": "SK-MA-0020", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0019", "node": "SK-MA-0004", "kind": "supports"},
    {"prerequisite": "SK-MA-0020", "node": "SK-MA-0004", "kind": "supports"},
    {"prerequisite": "SK-MA-0001", "node": "SK-MA-0010", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0001", "node": "SK-MA-0011", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0031", "node": "SK-MA-0029", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0007", "node": "SK-MA-0021", "kind": "supports"},
    {"prerequisite": "SK-MA-0021", "node": "SK-MA-0029", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0029", "node": "SK-MA-0030", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0007", "node": "SK-MA-0030", "kind": "supports"},
    {"prerequisite": "SK-MA-0009", "node": "SK-MA-0026", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0010", "node": "SK-MA-0013", "kind": "supports"},
    {"prerequisite": "SK-MA-0011", "node": "SK-MA-0013", "kind": "supports"},
    {"prerequisite": "SK-MA-0013", "node": "SK-MA-0027", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0013", "node": "SK-MA-0028", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0023", "node": "SK-MA-0027", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0024", "node": "SK-MA-0027", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0015", "node": "SK-MA-0027", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0015", "node": "SK-MA-0028", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0027", "node": "SK-MA-0016", "kind": "supports"},
    {"prerequisite": "SK-MA-0028", "node": "SK-MA-0016", "kind": "supports"},
    {"prerequisite": "SK-MA-0033", "node": "SK-MA-0010", "kind": "supports"},
    {"prerequisite": "SK-MA-0033", "node": "SK-MA-0011", "kind": "supports"},
    {"prerequisite": "SK-MA-0033", "node": "SK-MA-0029", "kind": "supports"},
    {"prerequisite": "SK-MA-0024", "node": "SK-MA-0034", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0051", "node": "SK-MA-0035", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0036", "node": "SK-MA-0038", "kind": "supports"},
    {"prerequisite": "SK-MA-0005", "node": "SK-MA-0038", "kind": "supports"},
    {"prerequisite": "SK-MA-0039", "node": "SK-MA-0021", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0039", "node": "SK-MA-0040", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0066", "node": "SK-MA-0040", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0041", "node": "SK-MA-0026", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0042", "node": "SK-MA-0026", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0044", "node": "SK-MA-0010", "kind": "supports"},
    {"prerequisite": "SK-MA-0044", "node": "SK-MA-0011", "kind": "supports"},
    {"prerequisite": "SK-MA-0046", "node": "SK-MA-0047", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0047", "node": "SK-MA-0048", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0066", "node": "SK-MA-0048", "kind": "supports"},
    {"prerequisite": "SK-MA-0048", "node": "SK-MA-0049", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0049", "node": "SK-MA-0010", "kind": "supports"},
    {"prerequisite": "SK-MA-0049", "node": "SK-MA-0011", "kind": "supports"},
    {"prerequisite": "SK-MA-0049", "node": "SK-MA-0029", "kind": "supports"},
    {"prerequisite": "SK-MA-0051", "node": "SK-MA-0053", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0051", "node": "SK-MA-0054", "kind": "supports"},
    {"prerequisite": "SK-MA-0056", "node": "SK-MA-0054", "kind": "supports"},
    {"prerequisite": "SK-MA-0062", "node": "SK-MA-0054", "kind": "supports"},
    {"prerequisite": "SK-MA-0054", "node": "SK-MA-0055", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0052", "node": "SK-MA-0055", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0053", "node": "SK-MA-0055", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0056", "node": "SK-MA-0058", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0057", "node": "SK-MA-0058", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0057", "node": "SK-MA-0052", "kind": "supports"},
    {"prerequisite": "SK-MA-0059", "node": "SK-MA-0061", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0060", "node": "SK-MA-0046", "kind": "supports"},
    {"prerequisite": "SK-MA-0061", "node": "SK-MA-0010", "kind": "supports"},
    {"prerequisite": "SK-MA-0061", "node": "SK-MA-0011", "kind": "supports"},
    {"prerequisite": "SK-MA-0062", "node": "SK-MA-0064", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0063", "node": "SK-MA-0055", "kind": "prerequisite"},
    {"prerequisite": "SK-MA-0064", "node": "SK-MA-0065", "kind": "supports"},
]
