# Generated by Django 5.2.15 on 2026-07-31 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0004_knowledgenode_hours_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('max_primary_score', models.PositiveSmallIntegerField()),
                ('primary_to_scaled', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uniq_active_exam_profile')],
            },
        ),
        migrations.CreateModel(
            name='ExamTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('exam_part', models.PositiveSmallIntegerField(choices=[(1, 'Part1'), (2, 'Part2')], default=1)),
                ('max_score', models.PositiveSmallIntegerField(default=1)),
                ('difficulty', models.PositiveSmallIntegerField(default=3)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='exams.examprofile')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ExamTaskSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.knowledgenode')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='exams.examtask')),
            ],
        ),
        migrations.AddField(
            model_name='examtask',
            name='nodes',
            field=models.ManyToManyField(related_name='exam_tasks', through='exams.ExamTaskSkill', to='knowledge.knowledgenode'),
        ),
        migrations.AddConstraint(
            model_name='examtaskskill',
            constraint=models.UniqueConstraint(fields=('task', 'node'), name='uniq_task_node'),
        ),
        migrations.AddConstraint(
            model_name='examtask',
            constraint=models.UniqueConstraint(fields=('profile', 'number'), name='uniq_profile_task'),
        ),
    ]
