# Generated by Django 5.2.15 on 2026-09-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprofile',
            name='scale_is_official',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examtask',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
