# Generated by Django 5.2.16 on 2026-07-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aihintmessage',
            name='failed_claims',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aihintmessage',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aihintmessage',
            name='unverified_claims',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
