# Generated by Django 5.2.15 on 2026-10-03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ai_mentor", "0003_aihintmessage_usage")]

    operations = [
        migrations.CreateModel(
            name="AiOutboundRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pseudonym", models.CharField(db_index=True, max_length=28)),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("purpose", models.CharField(choices=[("hint", "Подсказка"), ("mock_check", "Проверка пробника")], max_length=24)),
                ("provider", models.CharField(max_length=80)),
                ("model", models.CharField(blank=True, max_length=160)),
                ("redaction_counts", models.JSONField(blank=True, default=dict)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("student", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_outbound_requests", to="accounts.studentprofile")),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
