# Generated by Django 5.2.15 on 2026-07-30 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_studentgroup_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'shop categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slot', models.CharField(choices=[('avatar', 'Avatar'), ('frame', 'Frame'), ('theme', 'Theme'), ('badge', 'Badge')], default='avatar', max_length=16)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('price_coins', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='economy.shopcategory')),
            ],
            options={
                'ordering': ['slot', 'price_coins', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(choices=[('xp_award', 'Xp Award'), ('daily_challenge', 'Daily Challenge'), ('homework_done', 'Homework Done'), ('lesson_done', 'Lesson Done'), ('mock_completed', 'Mock Completed'), ('mistake_resolved', 'Mistake Resolved'), ('purchase', 'Purchase'), ('admin_grant', 'Admin Grant'), ('refund', 'Refund')], max_length=32)),
                ('reference', models.CharField(max_length=64)),
                ('balance_after', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_coins', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='economy.wallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='accounts.studentprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='economy.shopitem')),
            ],
            options={
                'ordering': ['-acquired_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'item'), name='uniq_student_item')],
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('wallet', 'reason', 'reference'), name='uniq_ledger_event'),
        ),
    ]
