# Generated by Django 5.2.15 on 2026-08-02 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_studentprofile_forecast_calibration_and_more'),
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='code',
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='duration_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='effect',
            field=models.CharField(choices=[('none', 'Только внешний вид'), ('streak_freeze', 'Заморозка стрика'), ('xp_boost', 'Ускоритель опыта')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='effect_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='slot',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('frame', 'Frame'), ('theme', 'Theme'), ('badge', 'Badge'), ('boost', 'Boost')], default='avatar', max_length=16),
        ),
        migrations.CreateModel(
            name='XpBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_percent', models.PositiveSmallIntegerField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boosts', to='economy.shopitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_boosts', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-ends_at'],
            },
        ),
    ]
