# Generated by Django 5.2.15 on 2026-09-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_shopitem_code_shopitem_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='tier',
            field=models.CharField(choices=[('base', 'Базовый'), ('paid', 'Покупной'), ('animated', 'Анимированный')], default='paid', max_length=16),
        ),
    ]
