# Generated by Django 5.2.15 on 2026-09-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_remove_rocket_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='slot',
            field=models.CharField(choices=[('avatar', 'Аватар'), ('frame', 'Рамка'), ('theme', 'Тема'), ('badge', 'Значок'), ('boost', 'Ускоритель')], default='avatar', max_length=16),
        ),
    ]
