# Generated by Django 5.2.15 on 2026-10-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0005_alter_shopitem_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopitem",
            name="tier",
            field=models.CharField(
                choices=[
                    ("base", "Базовый"),
                    ("paid", "Покупной"),
                    ("animated", "Анимированный"),
                    ("reward", "Награда лиги"),
                ],
                default="paid",
                max_length=16,
            ),
        ),
    ]
