# Generated by Codex on 2026-10-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0006_alter_shopitem_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopitem",
            name="tier",
            field=models.CharField(
                choices=[
                    ("base", "Базовый"),
                    ("paid", "Покупной"),
                    ("animated", "Анимированный"),
                    ("reward", "Награда"),
                ],
                default="paid",
                max_length=16,
            ),
        ),
    ]
